// <auto-generated />
using System;
using Meta.IntroApp;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Meta.IntroApp.Migrations
{
    [DbContext(typeof(MetaITechDbContext))]
    [Migration("20210606080132_AddFeedBackTable")]
    partial class AddFeedBackTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Meta.IntroApp.Account", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<int>("AccountType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConfirmationCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ConfirmationCodeEndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsCodeConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("MerchantId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("MerchantId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("Meta.IntroApp.AccountClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Meta.IntroApp.AccountLogin", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AccountLogins");
                });

            modelBuilder.Entity("Meta.IntroApp.AccountRole", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AccountRoles");
                });

            modelBuilder.Entity("Meta.IntroApp.AccountToken", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("Meta.IntroApp.DbModels.MobFeedBack", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long?>("AccountsId")
                        .HasColumnType("bigint");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MerchantId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SenderName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AccountsId");

                    b.HasIndex("MerchantId");

                    b.ToTable("FeedBacks");
                });

            modelBuilder.Entity("Meta.IntroApp.MobAbout", b =>
                {
                    b.Property<int>("AboutUsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Images")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MerchantId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AboutUsId");

                    b.HasIndex(new[] { "MerchantId" }, "MERCHANT_FK");

                    b.ToTable("MOB_ABOUT");
                });

            modelBuilder.Entity("Meta.IntroApp.MobAppointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("AppointmentDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("BookingDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("BranchId")
                        .HasColumnType("int");

                    b.Property<long>("ClientId")
                        .HasColumnType("bigint");

                    b.Property<string>("MerchantId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("WorkPlanId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "BranchId" }, "B_FK_idx");

                    b.HasIndex(new[] { "ClientId" }, "CLIENT_APPOINTMENT_FK_idx");

                    b.HasIndex(new[] { "MerchantId" }, "M_FK_idx");

                    b.HasIndex(new[] { "WorkPlanId" }, "W_P_APPOINTMENT_idx");

                    b.ToTable("MOB_APPOINTMENT");
                });

            modelBuilder.Entity("Meta.IntroApp.MobAppointmentDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AppointmentId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FromTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StaffId")
                        .HasColumnType("int");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("SubServiceId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ToTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "AppointmentId" }, "APPOINTMENT_FK_idx");

                    b.HasIndex(new[] { "StaffId" }, "STAFF_FK_idx");

                    b.HasIndex(new[] { "SubServiceId" }, "SU_SERVICE_FK_idx");

                    b.ToTable("MOB_APPOINTMENT_DETAILES");
                });

            modelBuilder.Entity("Meta.IntroApp.MobBranch", b =>
                {
                    b.Property<int>("BranchesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("'1'");

                    b.Property<int?>("IsMain")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("'1'");

                    b.Property<string>("MerchantId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BranchesId");

                    b.HasIndex(new[] { "MerchantId" }, "USER_FK");

                    b.ToTable("MOB_BRANCH");
                });

            modelBuilder.Entity("Meta.IntroApp.MobContact", b =>
                {
                    b.Property<int>("ContactUsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("BranchId")
                        .HasColumnType("int");

                    b.Property<int>("Channel")
                        .HasColumnType("int");

                    b.Property<int?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("'1'");

                    b.Property<int?>("IsSelected")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("'1'");

                    b.Property<string>("MerchantId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ContactUsId");

                    b.HasIndex(new[] { "BranchId" }, "BRANCH_ID_CONTACT");

                    b.HasIndex(new[] { "MerchantId" }, "USER_CONTACT_FK");

                    b.ToTable("MOB_CONTACT");
                });

            modelBuilder.Entity("Meta.IntroApp.MobGallery", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("BranchId")
                        .HasColumnType("int");

                    b.Property<int?>("IsFeatured")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("'1'");

                    b.Property<string>("MerchantId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MOB_GALLERY");
                });

            modelBuilder.Entity("Meta.IntroApp.MobGlobalTheme", b =>
                {
                    b.Property<int>("MobGlobalThemeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BackGroundColor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("BranchId")
                        .HasColumnType("int");

                    b.Property<string>("FontColor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FontType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("GallerySlider")
                        .HasColumnType("bit");

                    b.Property<string>("GlobalColor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LayoutOrder")
                        .HasColumnType("int");

                    b.Property<string>("LogoImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("MainSlider")
                        .HasColumnType("bit");

                    b.Property<string>("MerchantId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NavBarColor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("NewsSlider")
                        .HasColumnType("bit");

                    b.Property<bool>("ProjectSlider")
                        .HasColumnType("bit");

                    b.Property<bool>("ServicesSlider")
                        .HasColumnType("bit");

                    b.Property<string>("SideBarColor")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MobGlobalThemeId");

                    b.HasIndex(new[] { "BranchId" }, "BRANCH_THEME");

                    b.HasIndex(new[] { "MerchantId" }, "USER_THEME_FK");

                    b.ToTable("MOB_GLOBAL_THEME");
                });

            modelBuilder.Entity("Meta.IntroApp.MobImage", b =>
                {
                    b.Property<int>("ImagesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AboutUsId")
                        .HasColumnType("int");

                    b.Property<int?>("BranchesId")
                        .HasColumnType("int");

                    b.Property<int?>("ContactUsId")
                        .HasColumnType("int");

                    b.Property<string>("DataBase64")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int?>("IsCover")
                        .HasColumnType("int");

                    b.Property<int?>("IsFeatured")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("'1'");

                    b.Property<int?>("NewsId")
                        .HasColumnType("int");

                    b.Property<int?>("ProjectId")
                        .HasColumnType("int");

                    b.Property<int?>("ServiceId")
                        .HasColumnType("int");

                    b.Property<int?>("SubServiceId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ImagesId");

                    b.HasIndex(new[] { "BranchesId" }, "BRANCH_FK");

                    b.HasIndex(new[] { "NewsId" }, "NEWS_FK");

                    b.HasIndex(new[] { "ProjectId" }, "PROJECT");

                    b.HasIndex(new[] { "ServiceId" }, "SERVICE_FK");

                    b.HasIndex(new[] { "SubServiceId" }, "SUB_SERVICE_FK");

                    b.ToTable("MOB_IMAGE");
                });

            modelBuilder.Entity("Meta.IntroApp.MobMerchant", b =>
                {
                    b.Property<string>("MerchantId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Interval")
                        .HasColumnType("int");

                    b.Property<string>("MerchantName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MerchantId");

                    b.ToTable("MOB_MERCHANT");
                });

            modelBuilder.Entity("Meta.IntroApp.MobNews", b =>
                {
                    b.Property<int>("NewsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("BranchId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Images")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("'1'");

                    b.Property<int?>("IsPublished")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("'1'");

                    b.Property<string>("MerchantId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("PublishingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SubTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NewsId");

                    b.HasIndex(new[] { "BranchId" }, "BRANCH_ID_NEWS");

                    b.HasIndex(new[] { "MerchantId" }, "USER_NEWS_FK");

                    b.ToTable("MOB_NEWS");
                });

            modelBuilder.Entity("Meta.IntroApp.MobOurTeam", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("BranchId")
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Images")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("'1'");

                    b.Property<string>("MerchantId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Position")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmployeeId");

                    b.HasIndex(new[] { "BranchId" }, "BRANCH_ID_EMPLOYEE");

                    b.HasIndex(new[] { "MerchantId" }, "MERCHANT_EMPLOYEE_FK");

                    b.ToTable("MOB_OUR_TEAM");
                });

            modelBuilder.Entity("Meta.IntroApp.MobProject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("BranchId")
                        .HasColumnType("int");

                    b.Property<string>("ClientName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Images")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("'1'");

                    b.Property<string>("MerchantId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Period")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "BranchId" }, "BRANCH_ID");

                    b.HasIndex(new[] { "MerchantId" }, "PROJECT_MERCHANT_FK");

                    b.ToTable("MOB_PROJECT");
                });

            modelBuilder.Entity("Meta.IntroApp.MobService", b =>
                {
                    b.Property<int>("ServicesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("BranchId")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Icon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IconMobile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("'1'");

                    b.Property<string>("MerchantId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ServicesId");

                    b.HasIndex(new[] { "BranchId" }, "BRANCH_ID_SERVICES");

                    b.HasIndex(new[] { "MerchantId" }, "SERVICE_MERCHANT_FK");

                    b.ToTable("MOB_SERVICE");
                });

            modelBuilder.Entity("Meta.IntroApp.MobSlider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("BranchId")
                        .HasColumnType("int");

                    b.Property<int?>("IsFeatured")
                        .HasColumnType("int");

                    b.Property<string>("Link")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MerchantId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MOB_SLIDERS");
                });

            modelBuilder.Entity("Meta.IntroApp.MobStaffServiceAssign", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("StaffId")
                        .HasColumnType("int");

                    b.Property<int?>("SubServiceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "StaffId" }, "STAFF_FK_idx")
                        .HasDatabaseName("STAFF_FK_idx1");

                    b.HasIndex(new[] { "SubServiceId" }, "S_SERVICE_FK_idx");

                    b.ToTable("MOB_STAFF_SERVICE_ASSIGN");
                });

            modelBuilder.Entity("Meta.IntroApp.MobSubService", b =>
                {
                    b.Property<int>("SubServicesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Icon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Images")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("'1'");

                    b.Property<int?>("IsFeatured")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("'1'");

                    b.Property<int?>("ServiceId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SubServicesId");

                    b.HasIndex(new[] { "ServiceId" }, "SERVICE_ID");

                    b.ToTable("MOB_SUB_SERVICE");
                });

            modelBuilder.Entity("Meta.IntroApp.MobWorkPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("BranchId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FirstWorkTimeEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FirstWorkTimeStart")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FromDay")
                        .HasColumnType("datetime2");

                    b.Property<string>("MerchantId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlanName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SecondWorkTimeEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("SecondWorkTimeStart")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ToDay")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "BranchId" }, "BRANCH_PLAN_FK_idx");

                    b.HasIndex(new[] { "MerchantId" }, "MERCHANT_PLAN_FK_idx");

                    b.ToTable("MOB_WORK_PLAN");
                });

            modelBuilder.Entity("Meta.IntroApp.Role", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Meta.IntroApp.RoleCalim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Meta.IntroApp.Account", b =>
                {
                    b.HasOne("Meta.IntroApp.MobMerchant", "Merchant")
                        .WithMany("Accounts")
                        .HasForeignKey("MerchantId");

                    b.Navigation("Merchant");
                });

            modelBuilder.Entity("Meta.IntroApp.AccountClaim", b =>
                {
                    b.HasOne("Meta.IntroApp.Account", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Meta.IntroApp.AccountLogin", b =>
                {
                    b.HasOne("Meta.IntroApp.Account", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Meta.IntroApp.AccountRole", b =>
                {
                    b.HasOne("Meta.IntroApp.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Meta.IntroApp.Account", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Meta.IntroApp.AccountToken", b =>
                {
                    b.HasOne("Meta.IntroApp.Account", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Meta.IntroApp.DbModels.MobFeedBack", b =>
                {
                    b.HasOne("Meta.IntroApp.Account", "Accounts")
                        .WithMany("FeedBacks")
                        .HasForeignKey("AccountsId");

                    b.HasOne("Meta.IntroApp.MobMerchant", "Merchant")
                        .WithMany("MobFeedBacks")
                        .HasForeignKey("MerchantId");

                    b.Navigation("Accounts");

                    b.Navigation("Merchant");
                });

            modelBuilder.Entity("Meta.IntroApp.MobAbout", b =>
                {
                    b.HasOne("Meta.IntroApp.MobMerchant", "Merchant")
                        .WithMany("MobAbouts")
                        .HasForeignKey("MerchantId")
                        .HasConstraintName("MERCHANT_FK");

                    b.Navigation("Merchant");
                });

            modelBuilder.Entity("Meta.IntroApp.MobAppointment", b =>
                {
                    b.HasOne("Meta.IntroApp.MobBranch", "Branch")
                        .WithMany("MobAppointments")
                        .HasForeignKey("BranchId")
                        .HasConstraintName("B_FK");

                    b.HasOne("Meta.IntroApp.Account", "Client")
                        .WithMany("Appointments")
                        .HasForeignKey("ClientId")
                        .HasConstraintName("CLIENT_APPOINTMENT_FK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Meta.IntroApp.MobMerchant", "Merchant")
                        .WithMany("MobAppointments")
                        .HasForeignKey("MerchantId")
                        .HasConstraintName("M_FK");

                    b.HasOne("Meta.IntroApp.MobWorkPlan", "WorkPlan")
                        .WithMany("MobAppointments")
                        .HasForeignKey("WorkPlanId")
                        .HasConstraintName("W_P_APPOINTMENT");

                    b.Navigation("Branch");

                    b.Navigation("Client");

                    b.Navigation("Merchant");

                    b.Navigation("WorkPlan");
                });

            modelBuilder.Entity("Meta.IntroApp.MobAppointmentDetails", b =>
                {
                    b.HasOne("Meta.IntroApp.MobAppointment", "Appointment")
                        .WithMany("MobAppointmentDetails")
                        .HasForeignKey("AppointmentId")
                        .HasConstraintName("APPOINTMENT_FK");

                    b.HasOne("Meta.IntroApp.MobSubService", "SubService")
                        .WithMany("MobAppointmentDetailes")
                        .HasForeignKey("SubServiceId")
                        .HasConstraintName("SU_SERVICE_FK");

                    b.Navigation("Appointment");

                    b.Navigation("SubService");
                });

            modelBuilder.Entity("Meta.IntroApp.MobBranch", b =>
                {
                    b.HasOne("Meta.IntroApp.MobMerchant", "Merchant")
                        .WithMany("MobBranches")
                        .HasForeignKey("MerchantId")
                        .HasConstraintName("USER_FK");

                    b.Navigation("Merchant");
                });

            modelBuilder.Entity("Meta.IntroApp.MobContact", b =>
                {
                    b.HasOne("Meta.IntroApp.MobBranch", "Branch")
                        .WithMany("MobContacts")
                        .HasForeignKey("BranchId")
                        .HasConstraintName("BRANCH_ID_CONTACT");

                    b.HasOne("Meta.IntroApp.MobMerchant", "Merchant")
                        .WithMany("MobContacts")
                        .HasForeignKey("MerchantId")
                        .HasConstraintName("USER_CONTACT_FK");

                    b.Navigation("Branch");

                    b.Navigation("Merchant");
                });

            modelBuilder.Entity("Meta.IntroApp.MobGlobalTheme", b =>
                {
                    b.HasOne("Meta.IntroApp.MobBranch", "Branch")
                        .WithMany("MobGlobalThemes")
                        .HasForeignKey("BranchId")
                        .HasConstraintName("BRANCH_THEME")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Meta.IntroApp.MobMerchant", "Merchant")
                        .WithMany("MobGlobalThemes")
                        .HasForeignKey("MerchantId")
                        .HasConstraintName("USER_THEME_FK");

                    b.Navigation("Branch");

                    b.Navigation("Merchant");
                });

            modelBuilder.Entity("Meta.IntroApp.MobImage", b =>
                {
                    b.HasOne("Meta.IntroApp.MobBranch", "Branches")
                        .WithMany("MobImages")
                        .HasForeignKey("BranchesId")
                        .HasConstraintName("BRANCH_FK");

                    b.HasOne("Meta.IntroApp.MobNews", "News")
                        .WithMany("MobImages")
                        .HasForeignKey("NewsId")
                        .HasConstraintName("NEWS_FK");

                    b.HasOne("Meta.IntroApp.MobProject", "Project")
                        .WithMany("MobImages")
                        .HasForeignKey("ProjectId")
                        .HasConstraintName("PROJECT");

                    b.HasOne("Meta.IntroApp.MobService", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId");

                    b.HasOne("Meta.IntroApp.MobSubService", "SubService")
                        .WithMany("MobImages")
                        .HasForeignKey("SubServiceId")
                        .HasConstraintName("SUB_SERVICE_FK");

                    b.Navigation("Branches");

                    b.Navigation("News");

                    b.Navigation("Project");

                    b.Navigation("Service");

                    b.Navigation("SubService");
                });

            modelBuilder.Entity("Meta.IntroApp.MobNews", b =>
                {
                    b.HasOne("Meta.IntroApp.MobBranch", "Branch")
                        .WithMany("MobNews")
                        .HasForeignKey("BranchId")
                        .HasConstraintName("BRANCH_ID_NEWS");

                    b.HasOne("Meta.IntroApp.MobMerchant", "Merchant")
                        .WithMany("MobNews")
                        .HasForeignKey("MerchantId")
                        .HasConstraintName("USER_NEWS_FK");

                    b.Navigation("Branch");

                    b.Navigation("Merchant");
                });

            modelBuilder.Entity("Meta.IntroApp.MobOurTeam", b =>
                {
                    b.HasOne("Meta.IntroApp.MobBranch", "Branch")
                        .WithMany("MobOurTeams")
                        .HasForeignKey("BranchId")
                        .HasConstraintName("BRANCH_ID_EMPLOYEE");

                    b.HasOne("Meta.IntroApp.MobMerchant", "Merchant")
                        .WithMany("MobOurTeams")
                        .HasForeignKey("MerchantId")
                        .HasConstraintName("MERCHANT_EMPLOYEE_FK");

                    b.Navigation("Branch");

                    b.Navigation("Merchant");
                });

            modelBuilder.Entity("Meta.IntroApp.MobProject", b =>
                {
                    b.HasOne("Meta.IntroApp.MobBranch", "Branch")
                        .WithMany("MobProjects")
                        .HasForeignKey("BranchId")
                        .HasConstraintName("BRANCH_ID");

                    b.HasOne("Meta.IntroApp.MobMerchant", "Merchant")
                        .WithMany("MobProjects")
                        .HasForeignKey("MerchantId")
                        .HasConstraintName("PROJECT_MERCHANT_FK");

                    b.Navigation("Branch");

                    b.Navigation("Merchant");
                });

            modelBuilder.Entity("Meta.IntroApp.MobService", b =>
                {
                    b.HasOne("Meta.IntroApp.MobBranch", "Branch")
                        .WithMany("MobServices")
                        .HasForeignKey("BranchId")
                        .HasConstraintName("BRANCH_ID_SERVICES");

                    b.HasOne("Meta.IntroApp.MobMerchant", "Merchant")
                        .WithMany("MobServices")
                        .HasForeignKey("MerchantId")
                        .HasConstraintName("SERVICE_MERCHANT_FK");

                    b.Navigation("Branch");

                    b.Navigation("Merchant");
                });

            modelBuilder.Entity("Meta.IntroApp.MobStaffServiceAssign", b =>
                {
                    b.HasOne("Meta.IntroApp.MobOurTeam", "Staff")
                        .WithMany("MobStaffServiceAssigns")
                        .HasForeignKey("StaffId")
                        .HasConstraintName("STAFF_FK");

                    b.HasOne("Meta.IntroApp.MobSubService", "SubService")
                        .WithMany("MobStaffServiceAssigns")
                        .HasForeignKey("SubServiceId")
                        .HasConstraintName("S_SERVICE_FK");

                    b.Navigation("Staff");

                    b.Navigation("SubService");
                });

            modelBuilder.Entity("Meta.IntroApp.MobSubService", b =>
                {
                    b.HasOne("Meta.IntroApp.MobService", "Service")
                        .WithMany("MobSubServices")
                        .HasForeignKey("ServiceId")
                        .HasConstraintName("SERVICE_ID");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("Meta.IntroApp.MobWorkPlan", b =>
                {
                    b.HasOne("Meta.IntroApp.MobBranch", "Branch")
                        .WithMany("MobWorkPlans")
                        .HasForeignKey("BranchId")
                        .HasConstraintName("BRANCH_PLAN_FK");

                    b.HasOne("Meta.IntroApp.MobMerchant", "Merchant")
                        .WithMany("MobWorkPlans")
                        .HasForeignKey("MerchantId")
                        .HasConstraintName("MERCHANT_PLAN_FK");

                    b.Navigation("Branch");

                    b.Navigation("Merchant");
                });

            modelBuilder.Entity("Meta.IntroApp.RoleCalim", b =>
                {
                    b.HasOne("Meta.IntroApp.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Meta.IntroApp.Account", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("FeedBacks");
                });

            modelBuilder.Entity("Meta.IntroApp.MobAppointment", b =>
                {
                    b.Navigation("MobAppointmentDetails");
                });

            modelBuilder.Entity("Meta.IntroApp.MobBranch", b =>
                {
                    b.Navigation("MobAppointments");

                    b.Navigation("MobContacts");

                    b.Navigation("MobGlobalThemes");

                    b.Navigation("MobImages");

                    b.Navigation("MobNews");

                    b.Navigation("MobOurTeams");

                    b.Navigation("MobProjects");

                    b.Navigation("MobServices");

                    b.Navigation("MobWorkPlans");
                });

            modelBuilder.Entity("Meta.IntroApp.MobMerchant", b =>
                {
                    b.Navigation("Accounts");

                    b.Navigation("MobAbouts");

                    b.Navigation("MobAppointments");

                    b.Navigation("MobBranches");

                    b.Navigation("MobContacts");

                    b.Navigation("MobFeedBacks");

                    b.Navigation("MobGlobalThemes");

                    b.Navigation("MobNews");

                    b.Navigation("MobOurTeams");

                    b.Navigation("MobProjects");

                    b.Navigation("MobServices");

                    b.Navigation("MobWorkPlans");
                });

            modelBuilder.Entity("Meta.IntroApp.MobNews", b =>
                {
                    b.Navigation("MobImages");
                });

            modelBuilder.Entity("Meta.IntroApp.MobOurTeam", b =>
                {
                    b.Navigation("MobStaffServiceAssigns");
                });

            modelBuilder.Entity("Meta.IntroApp.MobProject", b =>
                {
                    b.Navigation("MobImages");
                });

            modelBuilder.Entity("Meta.IntroApp.MobService", b =>
                {
                    b.Navigation("MobSubServices");
                });

            modelBuilder.Entity("Meta.IntroApp.MobSubService", b =>
                {
                    b.Navigation("MobAppointmentDetailes");

                    b.Navigation("MobImages");

                    b.Navigation("MobStaffServiceAssigns");
                });

            modelBuilder.Entity("Meta.IntroApp.MobWorkPlan", b =>
                {
                    b.Navigation("MobAppointments");
                });
#pragma warning restore 612, 618
        }
    }
}
